services:
  docs:
    image: django_overtuned_local_docs
    container_name: django_overtuned_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_overtuned:/app/django_overtuned:z
    ports:
      - '9000:9000'
    command: /start-docs
