log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'
    http:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':443'

  django:
    # https
    address: ':5000'

  flower:
    address: ':5555'

# certificatesResolvers:
#   letsencrypt:
#     # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
#     acme:
#       email: ''
#       storage: /etc/traefik/acme/acme.json
#       # https://doc.traefik.io/traefik/https/acme/#httpchallenge
#       httpChallenge:
#         entryPoint: web

http:
  routers:
    web-secure-router:
      rule: Host(`localhost`)
      entryPoints:
        - web-secure
      service: nextjs
      tls: {}
        # https://doc.traefik.io/traefik/routing/routers/#certresolver
        # certResolver: letsencrypt

    django-secure-router:
      rule: (Host(`localhost`) || Host(`traefik`))
      entryPoints:
        - django
      middlewares:
        - csrf
      service: django
      tls: {}
        # https://doc.traefik.io/traefik/routing/routers/#certresolver
        # certResolver: letsencrypt

    flower-secure-router:
      rule: 'Host(`localhost`)'
      entryPoints:
        - flower
      service: flower
      tls: {}
        # https://doc.traefik.io/traefik/master/routing/routers/#certresolver
        # certResolver: letsencrypt

    web-media-router:
      rule: '(Host(`localhost`) || Host(`traefik`)) && PathPrefix(`/media/`)'
      entryPoints:
        - django
      middlewares:
        - csrf
      service: django-media
      tls: {}
        # certResolver: letsencrypt

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    nextjs:
      loadBalancer:
        servers:
          - url: http://nextjs:3000
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
